### PR TITLE
Porting to ROS Kinetic

### PR DESCRIPTION
**Pull request by Sayter99**
This fixes problems in MathOPS.cs and fits catkin's environment.

1. Update the function **getRPY** in MathOPS.cs to avoid wrong results. For example, below matrices cannot be distinguished by original method.

* **Matrix A**

[ 0 -1  0 ]
[ 0  0 -1 ]
[ 1  0  0 ]

* **Matrix B**

[ 0  1  0 ]
[ 0  0  1 ]
[ 1  0  0 ]

2. There are some wrong paths in launch files, such as "robots" should be "urdf". These problems are corrected also.

3. Change manifest.xml to package.xml, add CMakeLists.txt to fit catkin's convention.

### CODE REVIEW

**Comment by gavanderhoorn** [comment]
Hi.

I *really* appreciate the PR, but I also really feel these changes should be submitted to [brawner/sw2urdf](https://bitbucket.org/brawner/sw2urdf) on BitBucket. That is the source repository for this mirror.

I'm sure @brawner would be happy to review your proposed changes and merge them if they solve issues that still exist.

**Comment by Sayter99** [comment]
@gavanderhoorn Thank for your reply.
I will try it!

**Comment by Sayter99** [comment]
@gavanderhoorn unfortunately, I cannot create a pull request on BitBucket.

**Comment by gavanderhoorn** [comment]
> @gavanderhoorn unfortunately, I cannot create a pull request on BitBucket.

not from Github no.

Do you have a bitbucket account and a fork of sw2urdf on there?

**Comment by Sayter99** [comment]
@gavanderhoorn Yes, I create an account and fork sw2urdf on BitBucket, but it doesn't seem to work.

**Pull request closed without merging**
